PetOwnerApplication/Models/Constants.cs
namespace PetOwnerApplication.Models
{
    public class Constants
    {
        public const string MemCacheAppSettings = "MemCacheEnabled";
        public const string ExtApiUserAgent = "ExtApiUserAgent";
        public const string UseProxy = "UseProxy";
        public const string ProxyUrl = "ProxyUrl";
        public const string ProxyPort = "ProxyPort";

        #region BaseController
        public const string area = "area";
        public const string controller = "controller";
        public const string action = "action";
        #endregion

        #region PetOwner
        public const string ApiUrl = "GetPetOwnerApiUrl";
        public const string GetLocalApiUrl = "GetLocalApiUrl";
        public const string PetOwnerCache = "PetOwnerCache";
        public const string EndPointName = "Pet";
        
        #endregion

        public enum Gender
        {
            Male,
            Female
        }

        public enum PetType
        {
            Cat,
            Dog,
            Fish
        }
    }
}

PetOwnerApplication/Models/PetDetail/Pet.cs
namespace PetOwnerApplication.Models.PetDetail
{
    using Newtonsoft.Json;
    using static PetOwnerApplication.Models.Constants;

    public class Pet
    {
        [JsonProperty("type")]
        public PetType Type { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; }
    }
}

PetOwnerApplication/Models/PetDetail/PetGroup.cs
namespace PetOwnerApplication.Models.PetDetail
{
    using System.Collections.Generic;
    using static PetOwnerApplication.Models.Constants;

    public class PetGroup
    {
        public string GroupName { get; set; }
        public List<string> PetNames { get; set; }
    }
}

PetOwnerApplication/Models/PetDetail/PetOwnerPerson.cs
namespace PetOwnerApplication.Models.PetDetail
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using static PetOwnerApplication.Models.Constants;

    public class PetOwnerPerson
    {
        [JsonProperty("name")]
        public string Name { get; set; }
        [JsonProperty("gender")]
        public Gender Gender { get; set; }
        [JsonProperty("age")]
        public int Age { get; set; }
        [JsonProperty("pets")]
        public List<Pet> Pets { get; set; }
    }
}

PetOwnerApplication/Models/ProxyDetail.cs
namespace PetOwnerApplication.Models
{
    public class ProxyDetail
    {
        public string Url { get; set; }
        public string Port { get; set; }
    }
}

PetOwnerApplication/Controllers/BaseController.cs
namespace PetOwnerApplication.Controllers
{
    using System.Web.Mvc;
    using Services;

    public class BaseController : Controller
    {
        public BaseController()
        {
        }

        public ViewResult Error()
        {
            return View("~/Views/Shared/Error.cshtml");
        }
    }
}

PetOwnerApplication/Controllers/PetController.cs
namespace PetOwnerApplication.Controllers
{
    using System.Threading.Tasks;
    using System.Web.Http;
    using PetOwnerApplication.Filters;
    using PetOwnerApplication.Utilities;
    using Services;
    using static PetOwnerApplication.Models.Constants;

    public class PetController : ApiController
    {
        private readonly IPetOwnerService _petService;

        public PetController(IPetOwnerService petService)
        {
            _petService = petService;
        }
        [Audit]
       public IHttpActionResult GetPet()
        {
            var result = _petService.GetPetDetailsByGenderGroup(PetType.Cat);
            if (result != null)
            {
                return Ok(result);
            }
            Logging.LogError("Pet Service Returned null.");
            return this.NotFound();
        }
    }
}

PetOwnerApplication/Controllers/PetDetailsController.cs
namespace PetOwnerApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Net.Http;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Models;
    using Models.PetDetail;
    using PetOwnerApplication.Filters;
    using PetOwnerApplication.Services;

    public class PetDetailsController : BaseController
    {
        public PetDetailsController() : base()
        {
            
        }
        [AuditAttribute]
        public async Task<ActionResult> Index()
        {
            var pets = new List<PetGroup>();
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(ConfigurationManager.AppSettings[Constants.GetLocalApiUrl]);
                    var responseTask = client.GetAsync(Constants.EndPointName);
                    await responseTask;

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<List<PetGroup>>();
                        await readTask;
                        pets = readTask.Result;
                    }
                }

                ViewBag.Title = "All Cats by their Owner's gender.";
                return View(pets);
            
        }
    }

}

PetOwnerApplication/Views/PetDetails/Index.cshtml
@model IEnumerable<PetOwnerApplication.Models.PetDetail.PetGroup>

@{
    ViewBag.Title = "Pet Owner Gender With Cat Details";
}

<h2>@ViewBag.Title</h2>

@if (null != Model && Model.Any())
{
    foreach (var pg in Model)
    {
        <ul>
            <li>
                @pg.GroupName
                @foreach (string petName in pg.PetNames)
                {
                    <ul>
                        <li>@petName</li>
                    </ul>
                }
            </li>
        </ul>
    }
}

PetOwnerApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pet Owner Details", "Index", "PetDetails", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Today.Date - Avik Ghosh</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>